version: '3.4'

services:
  grass-ndvimapbackend:
    container_name: grass-ndvimapbackend
    hostname:  grass-ndvimapbackend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4002:80"
    volumes:
      - /data:/app/Data
    networks:
      - global

networks:
  global:
    external: true