version: '3'

services:
  GazonNDVImap:
    container_name: GazonNDVImap
    hostname:  GazonNDVImap
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3002:80"
    volumes:
      - /data:/app/Data
    networks:
      - global

networks:
  global:
    external: true